name: Check

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  flake-check:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: cachix/install-nix-action@ab739621df7a23f52766f9ccc97f38da6b7af14f # v31.10.5
      - name: nix flake check
        run: nix flake check --no-build --show-trace
