name: Format

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  nixfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: cachix/install-nix-action@ab739621df7a23f52766f9ccc97f38da6b7af14f # v31.10.5
      - name: Check Nix formatting
        run: |
          nix run nixpkgs#nixfmt -- --check \
            $(find . -name '*.nix' -not -path './.git/*')
